// <auto-generated />
namespace BancoExt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v11));
        
        string IMigrationMetadata.Id
        {
            get { return "201903271302311_v11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
